/**
 * VideoThumbnail — non-playing video preview tile shown in chat bubbles.
 *
 * Three poster sources, in priority order — the FIRST one available is
 * used so paint is always instant when possible:
 *   1) `thumbnailUrl` prop  — JPEG generated by the SENDER's browser at
 *      send time and stored on the message. Best path: every recipient
 *      sees the real first frame on the very first paint, with zero
 *      per-device decoding work and zero black flash.
 *   2) localStorage cache  — JPEG captured locally on a previous visit
 *      (legacy videos that were sent before server-side thumbnails
 *      shipped). Survives reloads, scoped per video URL.
 *   3) On-the-fly capture  — last-resort fallback for legacy videos
 *      that have neither (1) nor (2). An off-screen <video> loads,
 *      seeks to 0.1 s, draws to canvas, JPEG-encodes, persists to
 *      localStorage so the next visit hits path 2.
 *
 * Only the still poster is rendered here. Tapping the tile fires
 * `onClick`, which in chat-area opens the full-screen MediaViewer
 * (where actual playback happens with native controls).
 *
 * Aspect-ratio resolution priority (so the bubble shape is correct on
 * the very first paint, no landscape→portrait flash):
 *   1) `intrinsicWidth` / `intrinsicHeight` props (server-stored).
 *   2) localStorage URL ratio cache.
 *   3) Off-screen <video> `loadedmetadata` event — last resort.
 *
 * BUBBLE-COLLAPSE BUG NOTE: when the chat message has no caption and
 * the bubble has no other text content, the bubble's width is driven
 * entirely by this component. If our visible <img> were absolutely
 * positioned (out of flow) the bubble would collapse to ~0 px wide.
 * To prevent that we ALWAYS render an in-flow sized element (either
 * the poster <img> or a transparent <svg> spacer) PLUS a `minWidth`
 * style on the container so the bubble has a sane width even before
 * the first paint of the poster image.
 */
import { useState, useEffect } from 'react';
import { Play, Loader2 } from 'lucide-react';

interface Props {
  src: string;
  /** Server-stored JPEG URL (set when the sender uploaded a thumbnail). */
  thumbnailUrl?: string | null;
  className?: string;
  intrinsicWidth?: number;
  intrinsicHeight?: number;
  onClick?: () => void;
}

// ── Aspect-ratio cache ────────────────────────────────────────────────
const aspectMemCache = new Map<string, number>();
const ASPECT_LS_PREFIX = 'tc:vra:';

function getCachedAspect(url: string): number | null {
  const m = aspectMemCache.get(url);
  if (m && isFinite(m) && m > 0) return m;
  try {
    const s = localStorage.getItem(ASPECT_LS_PREFIX + url);
    if (s) {
      const n = parseFloat(s);
      if (isFinite(n) && n > 0) {
        aspectMemCache.set(url, n);
        return n;
      }
    }
  } catch { /* localStorage unavailable */ }
  return null;
}
function setCachedAspect(url: string, r: number): void {
  if (!isFinite(r) || r <= 0) return;
  aspectMemCache.set(url, r);
  try { localStorage.setItem(ASPECT_LS_PREFIX + url, String(r)); } catch { /* quota */ }
}

// ── Local first-frame poster cache (fallback for legacy videos) ──────
const posterMemCache = new Map<string, string>();
const POSTER_LS_PREFIX = 'tc:vp:';

function getCachedPoster(url: string): string | null {
  const m = posterMemCache.get(url);
  if (m) return m;
  try {
    const s = localStorage.getItem(POSTER_LS_PREFIX + url);
    if (s) {
      posterMemCache.set(url, s);
      return s;
    }
  } catch { /* localStorage unavailable */ }
  return null;
}

function setCachedPoster(url: string, dataUrl: string): void {
  posterMemCache.set(url, dataUrl);
  const tryStore = () => localStorage.setItem(POSTER_LS_PREFIX + url, dataUrl);
  try {
    tryStore();
  } catch {
    // Likely quota exceeded — evict oldest poster keys and retry once.
    try {
      const keys: string[] = [];
      for (let i = 0; i < localStorage.length; i++) {
        const k = localStorage.key(i);
        if (k && k.startsWith(POSTER_LS_PREFIX)) keys.push(k);
      }
      const drop = Math.max(1, Math.ceil(keys.length * 0.2));
      for (let i = 0; i < drop; i++) localStorage.removeItem(keys[i]);
      tryStore();
    } catch { /* still failing — memory cache will keep working */ }
  }
}

/**
 * Read-only access to the local poster cache for a video URL.
 *
 * Returns the cached data URL string if any (memory or localStorage),
 * otherwise null. Used by the small reply previews and the conversation
 * details media tab so they can paint a real frame instantly when the
 * user has previously viewed the video — instead of a black box, a grey
 * `<video preload="metadata">` placeholder, or a network round-trip.
 */
export function getVideoPoster(videoUrl: string): string | null {
  return getCachedPoster(videoUrl);
}

/**
 * Pre-populate the poster cache for a video URL from a Blob.
 *
 * Called by chat-area the moment an outgoing video upload completes,
 * so that when the real server message subsequently replaces the
 * upload placeholder, the new VideoThumbnail finds the poster
 * already in cache and paints it on the very first frame — no
 * network fetch, no flash of the gradient background, no visible
 * blink during the placeholder→message swap.
 *
 * Best-effort: if FileReader fails or the dataURL is suspiciously
 * small, we silently no-op and the regular thumbnailUrl fetch path
 * takes over.
 */
export function cacheVideoPosterBlob(videoUrl: string, blob: Blob): void {
  try {
    const reader = new FileReader();
    reader.onload = () => {
      const dataUrl = reader.result;
      if (typeof dataUrl === 'string' && dataUrl.length > 1024) {
        setCachedPoster(videoUrl, dataUrl);
      }
    };
    reader.readAsDataURL(blob);
  } catch { /* ignore — cache write is purely an optimisation */ }
}

/**
 * Pre-populate the aspect-ratio cache for a video URL.
 *
 * Same idea as cacheVideoPosterBlob — primes the cache before the
 * VideoThumbnail mounts so the bubble lands at the correct shape
 * on the very first paint with no need to wait for metadata.
 */
export function cacheVideoAspect(videoUrl: string, ratio: number): void {
  if (isFinite(ratio) && ratio > 0) setCachedAspect(videoUrl, ratio);
}

function captureFrame(v: HTMLVideoElement, maxDim = 360): string | null {
  if (v.videoWidth <= 0 || v.videoHeight <= 0) return null;
  try {
    const canvas = document.createElement('canvas');
    const ratio = v.videoWidth / v.videoHeight;
    if (ratio >= 1) {
      canvas.width = maxDim;
      canvas.height = Math.round(maxDim / ratio);
    } else {
      canvas.height = maxDim;
      canvas.width = Math.round(maxDim * ratio);
    }
    const ctx = canvas.getContext('2d');
    if (!ctx) return null;
    ctx.drawImage(v, 0, 0, canvas.width, canvas.height);
    const out = canvas.toDataURL('image/jpeg', 0.7);
    if (out.length < 1024) return null;
    return out;
  } catch {
    return null;
  }
}

const DEFAULT_FALLBACK_ASPECT = 9 / 16;
// Defensive minimum so the bubble can't shrink to a tiny play-button-only
// box when the message has no caption — `w-full` on a child that's a
// shrink-to-fit flex item would otherwise resolve to ~0.
const MIN_TILE_WIDTH_PX = 240;

export function VideoThumbnail({
  src, thumbnailUrl, className = '', intrinsicWidth, intrinsicHeight, onClick,
}: Props) {
  const intrinsicRatio = (intrinsicWidth && intrinsicHeight && intrinsicHeight > 0)
    ? intrinsicWidth / intrinsicHeight
    : null;

  // Local cache wins outright when present — both because it's a
  // synchronous data URL (no network round-trip, no decode flash) AND
  // because chat-area pre-populates it the moment a video upload
  // completes, so the placeholder→real-message swap is seamless. When
  // there's no local cache we fall back to the server-stored
  // `thumbnailUrl` prop (which still loads instantly on a warm cache),
  // and finally to an on-the-fly capture for legacy videos that have
  // neither.
  const [aspect, setAspect] = useState<number | null>(
    () => intrinsicRatio ?? getCachedAspect(src),
  );
  const [localPoster, setLocalPoster] = useState<string | null>(
    () => getCachedPoster(src),
  );

  useEffect(() => {
    setAspect(intrinsicRatio ?? getCachedAspect(src));
    setLocalPoster(getCachedPoster(src));
  }, [src, intrinsicRatio, thumbnailUrl]);

  // Fall-through capture: only runs when neither the server thumbnail
  // nor the local cache has anything. Once we have a frame we persist
  // it so subsequent visits hit the cache and skip this entirely.
  useEffect(() => {
    if (thumbnailUrl) return;
    if (localPoster) return;
    let cancelled = false;
    let captured = false;

    const v = document.createElement('video');
    v.muted = true;
    v.playsInline = true;
    v.preload = 'metadata';
    // Append off-screen — iOS Safari sometimes refuses to decode frames
    // for fully-detached <video> elements.
    v.style.position = 'fixed';
    v.style.left = '-99999px';
    v.style.top = '-99999px';
    v.style.width = '1px';
    v.style.height = '1px';
    v.style.opacity = '0';
    v.style.pointerEvents = 'none';
    document.body.appendChild(v);
    v.src = `${src}#t=0.1`;

    const tryCapture = () => {
      if (cancelled || captured) return;
      if (v.readyState < 2) return;
      if (v.videoWidth > 0 && v.videoHeight > 0) {
        const r = v.videoWidth / v.videoHeight;
        setCachedAspect(src, r);
        setAspect(prev => prev ?? r);
      }
      const dataUrl = captureFrame(v);
      if (!dataUrl || cancelled) return;
      captured = true;
      setCachedPoster(src, dataUrl);
      setLocalPoster(dataUrl);
      v.src = '';
      v.load();
      v.remove();
    };

    v.addEventListener('loadeddata', tryCapture);
    v.addEventListener('seeked', tryCapture);
    v.addEventListener('canplay', tryCapture);
    const onErr = () => { if (!cancelled) v.remove(); };
    v.addEventListener('error', onErr);

    v.load();

    return () => {
      cancelled = true;
      v.removeEventListener('loadeddata', tryCapture);
      v.removeEventListener('seeked', tryCapture);
      v.removeEventListener('canplay', tryCapture);
      v.removeEventListener('error', onErr);
      v.src = '';
      try { v.remove(); } catch { /* already removed */ }
    };
  }, [src, thumbnailUrl, localPoster]);

  const effectiveAspect = aspect ?? DEFAULT_FALLBACK_ASPECT;
  // Local cache wins (data URL, instant); server thumbnail is the
  // backup so receivers without any local cache still get a real
  // poster on first paint.
  const visiblePoster = localPoster ?? thumbnailUrl;

  return (
    <div
      className={`relative overflow-hidden cursor-pointer select-none ${className}`}
      style={{
        aspectRatio: String(effectiveAspect),
        maxHeight: '70vh',
        minWidth: `${MIN_TILE_WIDTH_PX}px`,
        // Neutral near-black placeholder. The previous saturated purple
        // gradient created a very visible "purple flash" on incoming
        // videos that have no server-stored thumbnail (the on-the-fly
        // capture path takes ~1 s on a cold load — long enough for the
        // user to see the gradient and read it as a bug). A near-black
        // matte sits naturally inside the dark chat background and
        // reads as "loading" rather than a UI artefact, matching the
        // way Telegram's video tiles look before their thumbnail blob
        // decodes.
        background: 'rgba(20, 20, 26, 0.85)',
      }}
      onClick={onClick}
    >
      {visiblePoster ? (
        <img
          src={visiblePoster}
          alt=""
          className="block w-full h-full object-contain"
          draggable={false}
          // Decoded async to avoid blocking the main thread for the
          // brief moment the JPEG comes off cache/network.
          decoding="async"
        />
      ) : (
        // Transparent SVG placeholder that participates in the LAYOUT
        // FLOW (intrinsic 240×proportional dims) so the bubble has a
        // real width even when there's no caption to size it.
        <svg
          width={MIN_TILE_WIDTH_PX}
          height={Math.max(1, Math.round(MIN_TILE_WIDTH_PX / effectiveAspect))}
          className="block w-full h-full"
          aria-hidden
        />
      )}

      {!visiblePoster && (
        <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
          <Loader2 className="w-6 h-6 text-white/70 animate-spin" />
        </div>
      )}

      <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
        <div
          className="w-14 h-14 rounded-full flex items-center justify-center"
          style={{ background: 'rgba(0,0,0,0.55)', backdropFilter: 'blur(4px)' }}
        >
          <Play className="w-7 h-7 text-white ml-1" />
        </div>
      </div>
    </div>
  );
}
