import { pgTable, text, serial, timestamp, integer, jsonb, boolean } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const messagesTable = pgTable("messages", {
  id: serial("id").primaryKey(),
  conversationId: integer("conversation_id").notNull(),
  senderId: integer("sender_id").notNull(),
  content: text("content"),
  imageUrl: text("image_url"),
  // Intrinsic media dimensions captured at upload time so the receiving
  // client can size the bubble correctly on the very first paint — no
  // landscape→portrait flash, no loading placeholder. Both nullable for
  // backwards compatibility with rows created before these columns existed.
  mediaWidth: integer("media_width"),
  mediaHeight: integer("media_height"),
  // For video messages: URL to a server-stored JPEG of the first frame,
  // captured by the sender's browser at send time and uploaded alongside
  // the video. Lets every recipient see a real preview thumbnail on the
  // very first paint — no need to wait for their device to decode the
  // first frame, and no momentary black box. Nullable: pre-existing
  // videos and non-video messages don't have one.
  thumbnailUrl: text("thumbnail_url"),
  // Tiny base64 data URL (~32 px JPEG, ≈700–1500 bytes) generated by the
  // sender's browser at upload time. Embedded directly in the message
  // payload so receivers can paint a recognisable blurred preview of the
  // photo on the very first frame, BEFORE the multi-MB original finishes
  // downloading from object storage. Removes the long-lived "purple
  // placeholder" the user complained about on slow networks. Nullable:
  // pre-existing rows and non-image messages don't have one.
  mediaPreview: text("media_preview"),
  // Telegram-style "stripped thumbnail" — even smaller than mediaPreview
  // (~150-300 raw bytes vs the LQIP's 300-700) by removing the standard
  // JPEG header (quantization + Huffman + SOF0 tables) and reconstructing
  // it client-side from a hardcoded canonical prefix. Stored as base64 of
  // the Telegram wire format: [0x01, width_byte, height_byte, ...entropy
  // data from SOS through EOI]. See artifacts/api-server/src/lib/
  // strippedThumb.ts for the encoder and artifacts/telegram-pwa/src/lib/
  // stripped-thumb.ts for the decoder. Both sides agree on a fixed sharp
  // encoding profile (40x40 max, q50, no mozjpeg, no scan/code optim,
  // 4:2:0 chroma) so the prefix bytes are byte-identical across all
  // images. Nullable: pre-existing rows and non-image messages don't
  // have one. Coexists with mediaPreview — the client prefers stripped
  // when present and falls back to mediaPreview, then to the bare
  // aspect placeholder.
  mediaStrippedThumb: text("media_stripped_thumb"),
  audioUrl: text("audio_url"),
  audioDuration: integer("audio_duration"),
  pollId: integer("poll_id"),
  linkPreview: jsonb("link_preview"),
  mediaAlbum: jsonb("media_album"),
  replyToId: integer("reply_to_id"),
  // Call log fields (when message represents a call event, à la WhatsApp)
  callType: text("call_type"),       // 'audio' | 'video'
  callStatus: text("call_status"),   // 'missed' | 'answered' | 'declined' | 'ongoing'
  callDuration: integer("call_duration"), // seconds; null for missed/declined
  editedAt: timestamp("edited_at", { withTimezone: true }),
  isDeleted: boolean("is_deleted").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const reactionsTable = pgTable("reactions", {
  id: serial("id").primaryKey(),
  messageId: integer("message_id").notNull(),
  userId: integer("user_id").notNull(),
  emoji: text("emoji").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const pollsTable = pgTable("polls", {
  id: serial("id").primaryKey(),
  question: text("question").notNull(),
  isAnonymous: boolean("is_anonymous").notNull().default(true),
  isMultipleChoice: boolean("is_multiple_choice").notNull().default(false),
  isQuiz: boolean("is_quiz").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const pollOptionsTable = pgTable("poll_options", {
  id: serial("id").primaryKey(),
  pollId: integer("poll_id").notNull(),
  text: text("text").notNull(),
  sortOrder: integer("sort_order").notNull().default(0),
});

export const pollVotesTable = pgTable("poll_votes", {
  id: serial("id").primaryKey(),
  pollId: integer("poll_id").notNull(),
  optionId: integer("option_id").notNull(),
  userId: integer("user_id").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const insertMessageSchema = createInsertSchema(messagesTable).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertReactionSchema = createInsertSchema(reactionsTable).omit({
  id: true,
  createdAt: true,
});

export type InsertMessage = z.infer<typeof insertMessageSchema>;
export type Message = typeof messagesTable.$inferSelect;
export type InsertReaction = z.infer<typeof insertReactionSchema>;
export type Reaction = typeof reactionsTable.$inferSelect;
export type Poll = typeof pollsTable.$inferSelect;
export type PollOption = typeof pollOptionsTable.$inferSelect;
export type PollVote = typeof pollVotesTable.$inferSelect;
